language: python
branches:
  only:
  - master
  - devops
python:
  - "3.5"
  - "3.7"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - git submodule init
  - git submodule update
  - ./scripts/get_static_validation.sh
# command to install dependencies
install: 
  - pip install -r django_server/requirements.txt
  - (cd frontend && yarn install)
# command to run tests
script:
  - ./django_server/manage.py test
  - (cd frontend && yarn test)
