# Generated by Django 3.0 on 2020-01-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
