# Generated by Django 3.0 on 2020-01-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_profile_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='playlist',
        ),
    ]
